type: object
required:
  - packageId
  - summary
  - name
  - matching
  - status
properties:
  packageId:
    type: string
    description: Unique identifier for the package
  version:
    type: string
    description: > 
      The version of the package, which can be used for version control and tracking changes over time.
      Avoid using an increasing integer as the version number, as it may not accurately reflect the content changes. 
      Instead, consider using a hash of the package content or a combination of an internal ID and version number 
      to ensure uniqueness and integrity.
  summary:
    type: string
    description: A brief summary of the package, providing an overview of its contents or purpose.
  name:
    type: string
    description: The name of the package, which can be used for display purposes in user interfaces.
  matching:
    type: string
    description: Indicates the matching status of the package.
    enum: [match, partial-match]
  status:
    type: string
    description: The current status of the package.
    enum: 
    - offered
    - locked
    - expired
    - released
    - purchased
    - rollback
    - cancelled
    - fulfilled
    - refunded
    - exchanged
    - in_progress
    - completed
  elements:
    type: array
    description: A list of elements that are part of the package
    items:
      oneOf:
        - $ref: .\TravelRight.yaml
        - $ref: .\Ancillary.yaml
        - $ref: .\Allocation.yaml
        - $ref: .\AfterSalesFee.yaml
      discriminator:
        propertyName: packageElementType
        mapping:
          travelRight: .\TravelRight.yaml
          ancillary: .\Ancillary.yaml
          allocation: .\Allocation.yaml
          afterSalesFee: .\AfterSalesFee.yaml
  minimumPrice:
    $ref: .\Cost.yaml
  summaryDetails:
    type: array
    description: A list of detailed summaries related to the package, providing additional context or information.
    items:
      $ref: .\SummaryDetail.yaml
  trip:
    $ref: .\Trip.yaml
  guarantees:
    type: array
    description: A list of guarantees
    items:
      $ref: .\Guarantee.yaml
  links:
    type: array
    description: A list of links related to the package, which can provide additional information or actions.
    items:
      $ref: .\Link.yaml
example:
  {
    "packageId": "PK-123",
    "summary": "This is a sample package.",
    "name": "Sample Package",
    "matching": "match",
    "status": "offered",
    "minimumPrice": { "amount": 100.00, "currency": "USD" },
    "summaryDetails": [
      { 
        "detailType": "geospatial",
        "description": "A route from San Francisco to Los Angeles.",
        "content": { "type": "Feature", "geometry": { "type": "LineString", "coordinates": [[-122.4194, 37.7749], [-118.2437, 34.0522]] } }
      },
      { 
        "detailType": "condition",
        "content": "No pets allowed"
      }
    ],
    "elements": [
      {
        "elementType": "travelRight",
        "packageElementId": "PE-123",
        "numberOfAvailableItems": "5",
        "covering": [ { "startLeg": "L-789", "endLeg": "L-789" } ],
        "price": { "amount": 23.20, "currency": "EUR" },
        "travellingEntities": [ "TE-123", "TE-456" ]
      }, 
      {
        "elementType": "allocation",
        "packageElementId": "PE-124",
        "allocationType": "spot",
        "typeOfSpot": "seat",
        "numberOfAllocatedUnits": 1,
        "reference": "102/36B",
        "appliesTo": [ "PE-123" ]
      }
    ],
    "links": [
      {
        "rel": "lock",
        "href": "https://api.example.com/packages/PK-123/lock",
        "method": "POST",
        "type": "application/json"
      }
    ]
  }